name: flutter_secure_storage_example
description: Demonstrates how to use the flutter_secure_storage plugin.

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: '>=1.26.0-17.6.pre <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true