name: Integration test

on:
  push:
    branch: [develop, ci]
    pull_request: [develop] 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - run: |
        flutter config --enable-linux-desktop
        sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libsecret-1-dev libsecret-1-0 libjsoncpp-dev libjsoncpp1 gnome-keyring 
    - run: |
        cat <<'EOF' >> run.sh
          #!/bin/bash
          echo "" | gnome-keyring-daemon --unlock
          cd example 
          flutter drive --target=test_driver/app.dart -d linux -v
        EOF
        chmod +x run.sh
        dbus-run-session -- ./run.sh

